### ISSUE TITLE
[Suggestion] Time Line

### ISSUE THREAD

**Issue by Vanheden** [yesilmen-vm/YesilCMS#1]
Hello. Suggestion to add a Timeline page like Nostalrius had and all the other vanilla servers :)

**Comment by yesilmen-vm** [comment]
This feature has been added, please refer to: https://github.com/yesilmen-vm/YesilCMS/commit/717f2ced29d51e7697577555058817437255d8d8

Demo: https://yesilcms.page/en/timeline
