### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by huaijiuwow** [yesilmen-vm/YesilCMS#10]
I finished installation 1/2，but i continue it,write the setting to file. Web display:
Not Found

The requested URL /en/ was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by yesilmen-vm** [comment]
Please follow installation guideline. If you are installing locally, follow the notification messages on first page of installation step.

**Comment by ablohme86** [comment]
Cant this be used with apache? I also get the same error, but cant find an installation manual
