### ISSUE TITLE
isValidIpPort too restrictive

### ISSUE THREAD

**Issue by christophbrosch** [yesilmen-vm/YesilCMS#13]
I'm attempting to set up your repository as part of docker-compose environment. When testing the connection during the installation step, I ran into issues related to the `isValidIpPort` function. This issue comes from the fact that, given the docker-compose environment, the host can be given any string name the user declares inside the docker-compose.yml file.  To solve this issue I had to manually remove the `isValidIpPort` call from the if-statement. Attached is an example of how the installation form could be filled out in an docker-compose environment.

![image](https://github.com/yesilmen-vm/YesilCMS/assets/44674265/00f5a500-439e-4b23-a076-ad36906e74fd)

If you'd like I can contribute my Dockerfile and make minor changes to index.php inside the installation folder and send them your way via a PR.

Thank you for your awesome work!

**Comment by yesilmen-vm** [comment]
Hello, nice catch; I will modify the function to detect if its in docker env and act accordingly. Dockerfile would be nice :)
