### ISSUE TITLE
Timeline issue

### ISSUE THREAD

**Issue by stefan4628** [yesilmen-vm/YesilCMS#19]
After opens the link of the timeline , the pictures and content cannot be clearly displayed and cannot work correctly like the demo.

![image](https://github.com/yesilmen-vm/YesilCMS/assets/167276772/80565455-509e-47fb-86cc-90e16ab17d9c)
![image](https://github.com/yesilmen-vm/YesilCMS/assets/167276772/6441bb4a-a344-48d3-a619-aee9651544b9)

**Comment by lightningcal** [comment]
You can fix this by copying an .htaccess from one of the other modules into the assets folder of this module:
application\modules\timeline\assets\.htaccess

Without an .htaccess file your server will return a 403 error for the js files needed by the timeline module.
