### ISSUE TITLE
Hi, I got an error as below. how to solove it?

### ISSUE THREAD

**Issue by william19831103** [yesilmen-vm/YesilCMS#2]
Forbidden
You don't have permission to access /installation/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by yesilmen-vm** [comment]
Hello,

These errors (`permission` and `ErrorDocument`) are related with configuration of your system.

You can solve permission issue by using `chown` and `chmod` command. For `ErrorDocument` issue, check your `apache` configuration.
