### ISSUE TITLE
not found item in armory and database

### ISSUE THREAD

**Issue by Arshiya051** [yesilmen-vm/YesilCMS#24]
Hello and good time. It doesn't show the items well in the search database and armory, and it doesn't show the details of the items. Please help.
[![Uploading Screenshot 2024-08-30 082113.jpg…]()](https://s8.uupload.ir/files/screenshot_2024-08-30_082113_pc0d.jpg)
@yesilmen-vm 
@Nolin7777

**Comment by yesilmen-vm** [comment]
Hello, screenshot is not available. Make sure your core is compatible with the CMS.
