### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by benvalmont** [yesilmen-vm/YesilCMS#25]
Hi, my website is working but look like this --- Any Idea why ?
![Screenshot_6](https://github.com/user-attachments/assets/79635658-0d59-4437-bc74-b4471cc3f5e9)

Best Regards
Ben

**Comment by yesilmen-vm** [comment]
Hello, probably you pointed to an invalid domain since you are accessing through IP. Make your your base_url matches.

**Comment by benvalmont** [comment]
Thanks, Sorted
