### ISSUE TITLE
Need help,

### ISSUE THREAD

**Issue by william19831103** [yesilmen-vm/YesilCMS#3]
Hi Yesilmen, how are you I met some  problems.

MySQL Version: 5.7.31
PHP Version: 7.3.4
Webhost or Xampp(ETC):  Xampp
Latest Version (Yes/No): Yes

1.  I registerd new accout, but I got error as below:
"
A Database Error Occurred
Error Number: 1146

Table 'realmd.battlenet_accounts' doesn't exist

INSERT INTO `battlenet_accounts` (`id`, `email`, `sha_pass_hash`) VALUES ('3', 'test1@gmail.com', '0F4E40A66371D6468A2F091641761E6FC3223149C980CE201762A8EB79D5B9A6')

Filename: C:/phpstudy_pro/WWW/system/database/DB_driver.php

Line Number: 692

"

2.  I loged into with my gm accout which was created by gm command. but I can not find the admin panel entry, just nomal user panel, it is does not same as blizzcms.

At last Thanks for your great work.

**Comment by yesilmen-vm** [comment]
Hi @william19831103,

1 - Which core are you using? If you are using VMaNGOS there shouldn't be any `battlenet_accounts` table. Please try disabling Bnet
2 - By default account with `gmlevel` > 3 should be able to login to Admin Panel.

**Comment by william19831103** [comment]
Hi Yesilmen, I used core V18 or V19.  
About website settings of Emulator,  which one i should choose, vMangso/Cmangos(Manogs), or Battle.Net(Sha_pass_hass).
If i choose Battle.Net(Sha_pass_hass). it will shows error that can't find battlenet_accounts.
if i choose vMangso/Cmangos(Manogs), no erros about can't find battlenet_accounts. but I set my  account gmlevel as 6 or 4, still can not see the admin panel,Thanks a lot

**Comment by william19831103** [comment]
I clicked store, shows erroe as below:

An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Filename: C:\phpstudy_pro\WWW\application\modules\store\models\Store_model.php

Line Number: 11

Backtrace:

File: C:\phpstudy_pro\WWW\application\third_party\MX\Loader.php
Line: 359
Function: load_file

File: C:\phpstudy_pro\WWW\application\modules\store\controllers\Store.php
Line: 17
Function: model

File: C:\phpstudy_pro\WWW\index.php
Line: 296
Function: require_once

**Comment by yesilmen-vm** [comment]
This has been fixed, it was related with PHP version (typed properties).
