### ISSUE TITLE
can not run composer update in ubutu 22.04, PHP 8.1.2

### ISSUE THREAD

**Issue by rogical** [yesilmen-vm/YesilCMS#8]
root@r02:/var/www/YesilCMS# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ~7.2 but your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires laizerox/php-wowemu-auth ^1.0 -> satisfiable by laizerox/php-wowemu-auth[v1.0.0].
    - laizerox/php-wowemu-auth v1.0.0 requires php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.

root@r02:/var/www/YesilCMS# lsb_release -a; php -v
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.11, Copyright (c), by Zend Technologies
root@r02:/var/www/YesilCMS#

**Comment by yesilmen-vm** [comment]
Hello, Problem 1 is fixed, please refer to b9e84ea159bc5b62c7b3a2f687d8cb8fe11820fc

Problem 2 is 3rd party package that we use for Auth method and I cannot modify that, but as a workaround you could simply run composer with `composer install --ignore-platform-reqs` command.
